name: DDG-Survival
main: com.barancode.mc.ddg.survival.Main
version: 1.0
author: BaranCODE
website: http://mc.barancode.com
load: STARTUP

commands:
   sethome:
      usage: /sethome
   home:
      usage: /home
   tpa:
      usage: /tpa <player>
   tpaaccept:
      usage: /tpaaccept
      aliases: [tpaccept]
   tpdeny:
      usage: /tpdeny
   chunks:
      usage: /chunks
   chunk:
      usage: /chunk <claim | info | declaim | setowner>
   setpoints:
      usage: /setpoints <player> <points>
   setpower:
      usage: /setpower <player> <power>
   points:
      usage: /points [player]
   power:
      usage: /power [player]
   ban:
      usage: /ban <player> <reason> [ t:<Days:d> <Hours:h> <Minutes:m> ]
   kick:
      usage: /kick <player> <reason>
   unban:
      usage: /unban <player>
   broadcast:
      usage: /broadcast <message>
   fly:
      usage: /fly
   chunkban:
      usage: /chunkban <player>
   chunkunban:
      usage: /chunkunban <player>
   chunkmute:
      usage: /chunkmute <player>
   chunkunmute:
      usage: /chunkunmute <player>
   friend:
      usage: /friend <add | remove> <player>
   vote:
      usage: /vote <up | down>
   setbook:
      usage: /setbook
   togglearrow:
      usage: /togglearrow
permissions:
    survival.fly:
        default: op
    survival.admin:
        default: op
    survival.nether:
        default: op
    survival.doublejump:
        default: op
    survival.broadcast:
        default: op
    survival.keepitems:
        default: op
    survival.max:
        default: op