name: VantiRanks
main: com.barancode.mc.vantiranks.Main
version: 1.0
author: BaranCODE
website: http://mc.barancode.com
depend: [Vault]

commands:
   rank:
      description: Rank command
      usage: /rank <name> <rank>
   reloadranks:
      description: Reload ranks
      usage: /reloadranks
      permission: ranks.reload
permissions:
    ranks.reload:
        default: op