is-hub: false
thanks: "&2[&aVotes&2] &6Thanks for voting! You have received 20 tokens"
broadcast: "&2[&aVotes&2] &3<player> has voted for The BCMC Network on <source>, and has received 20 tokens"
month: 9