name: KingdomWarnings
main: com.barancode.mc.kingdomwarnings.Main
version: 1.0
author: BaranCODE
website: http://mc.barancode.com

commands:
   kingdomban:
      description: Ban a person
   kingdomunban:
      description: Unban a person
   waarschuwing:
      description: Warnings
permissions:
    waarschuwing.zie:
        default: op
    waarschuwing.geef:
        default: op