name: SurvivalGames
version: ${project.version}.${BUILD_NUMBER}
main: org.mcsg.survivalgames.SurvivalGames
authors: [Double0negative]
description: Fully Automated Hunger Games Plugin!
depend: [WorldEdit, Vault]

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

