name: GoblinGames
main: GobBob.games.src.ThePlugin
version: 1.0
description: >
         	GobBob's MiniGame Plugin
commands:
  killall:
    description: Kills all the entities.
  killplayers:
    description: Kills all the players.
  killplayer:
    description: Kills the specified player.
  spawn:
    description: Spawn a mob.
  spawnstack:
    description: Spawn a stack of mobs.
  settokens:
    description: Some.