name: DDG-Survival-PVP
main: com.barancode.mc.ddg.survival.pvp.Main
version: 1.0
author: BaranCODE
website: http://mc.barancode.com

commands:
   spawnvillager:
      usage: /spawnvillager
      permission: survival.admin