name: SurvivalFly
main: com.barancode.mc.kingdomfly.Main
version: 1.0
author: BaranCODE
website: http://mc.barancode.com

commands:
   fly:
      description: Toggle flying
      usage: /fly
permissions:
    survival.fly:
        default: op
    survival.flyothers:
        default: op