name: ChoiceSelector
main: main.java.com.barancode.choiceselector.Main
version: 1.0
author: BaranCODE
website: http://barancode.com

commands:
  menureload:
    permission: menu.reload
permissions:
  menu.reload:
    default: op