host: 127.0.0.1
username: user
password: 1234
database: Userdata

INVALID_USERNAME: "Invalid username!"
KICK_NEW: "Please come back later. Mojang servers are down, but you're joining\n ChoiceCraft for the first time, so we have to authenticate you!"
KICK_IP: "Please come back later. Mojang servers are down, and your IP address isn't the same as your last one."