spawns:
  '1':
    x: 18
    y: 68
    z: 18
  '2':
    x: 18
    y: 68
    z: -18
  '3':
    x: -18
    y: 68
    z: -18
  '4':
    x: -18
    y: 68
    z: 18
first-join-spawn:
  x: 0
  y: 132
  z: 0
lobby-altitude: 100