name: BuildGuess
main: com.barancode.buildguess.Main
version: 1.0
author: BaranCODE
website: http://barancode.com

commands:
  setspawn:
    permission: spawn.set
  setbuildspawn:
    permission: spawn.set.build
  setpos:
    permission: spawn.set.position
    usage: /setpos <build or rollback> <1 or 2>
  setbook:
    permission: book.set
permissions:
  spawn.set:
    default: op
  spawn.set.build:
    default: op
  spawn.set.position:
    default: op
  book.set:
    default: op
  tips.vip:
    default: op