name: MyItems
main: com.barancode.mc.myitems.Main
version: 1.7
author: BaranCODE
website: http://mc.barancode.com

commands:
   myitems:
      description: MyItems command
      aliases: mi
      usage: /mi
permissions:
    myitems.create:
        default: op
    myitems.setlore:
        default: op
    myitems.setcommand:
        default: op
    myitems.get:
        default: op
    myitems.use.*:
        default: op
    myitems.list:
        default: op
    myitems.delete:
        default: op