name: BuildingContest
main: com.barancode.mc.contest.CreativeContest
version: 1.4
author: BaranCODE
website: http://mc.barancode.com

commands:
   contest:
      description: The commands for building contest
      usage: /contest
      permission: contest.user
      permission-message: You don't have permission for <permission>
   review:
      description: The judge commands for building contest
      usage: /review
      permission: contest.review
      permission-message: You don't have permission for <permission>
   contestadmin:
      description: The admin commands for building contest
      usage: /contestadmin
      permission: contest.admin
      permission-message: You don't have permission for <permission>
   contestreload:
      description: Reload building contest plugin
      usage: /contestreload
      permission: contest.reload
      permission-message: You don't have permission for <permission>
permissions:
    contest.user:
        description: The commands for building contest
        default: true
    contest.review:
        description: The judge commands for building contest
        default: op
    contest.admin:
        description: The admin commands for building contest
        default: op
    contest.reload:
        description: Reload building contest plugin
        default: op
    contest.delete:
        description: Delete a submission
        default: op