name: JumpingBlocks
main: com.barancode.mc.jumpingblocks.Main
version: 1.1
author: BaranCODE
website: http://mc.barancode.com

commands:
   jumpingblock:
      description: Jumping block commands
      usage: /jumpingblock
permissions:
    jumpingblock.create:
        default: op
    jumpingblock.delete:
        default: op